### ISSUE TITLE
不建议直接使用 GlobalEventChannel

### ISSUE THREAD

**Issue by cssxsh** [BakaBotTeam/wiki-search-mirai#1]
**Describe the bug**
https://github.com/BakaBotTeam/wiki-search-mirai/blob/a16bec0ed1b7968ecc55083d2b57de9993633f46/src/main/kotlin/ltd/guimc/wikisearch/PluginMain.kt#L54-L56
**To Reproduce**

...

**Expected behavior**

你应该使用 globalEventChannel()
```
// this 可以是插件类
this.globalEventChannel()
```

**Screenshots**

**Additional context**

**Comment by guimc233** [comment]
好的 感谢建议

我等明天回家改一下

**Comment by guimc233** [comment]
如果方便的话 可以直接帮忙发个pr吗
